# -----------------------------------------------
# Code generated by infractl. DO NOT EDIT. GCP
# _       __     __    ______     __ __      __             __
#| |     / /__  / /_  / ____/  __/ //_/_  __/ /_  ___  ____/ /
#| | /| / / _ \/ __ \/ __/ | |/_/ ,< / / / / __ \/ _ \/ __  /
#| |/ |/ /  __/ /_/ / /____>  </ /| / /_/ / /_/ /  __/ /_/ /
#|__/|__/\___/_.___/_____/_/|_/_/ |_\__,_/_.___/\___/\__,_/
#
# codegen-version: v7.4.4
# template-version: EXPERIMENTAL
# -----------------------------------------------

data "google_client_config" "default" {}

data "vault_generic_secret" "gcp_infra_credential" {
  path=replace("secret/data/eticcprod/infra/scratch/gcp-test", "/data/", "/")
}

resource "google_project_iam_custom_role" "prassark-role" {
  role_id     = "prassark_role"
  title       = "prassark Role"
  description = "prassark access to GCP services like GKE"
  # Based on https://cloud.google.com/kubernetes-engine/docs/how-to/iam
  permissions = [ "container.apiServices.create",
                  "container.apiServices.delete",
                  "container.apiServices.get",
                  "container.apiServices.getStatus",
                  "container.apiServices.list",
                  "container.apiServices.update",
                  "container.apiServices.updateStatus",
                  "container.auditSinks.create",
                  "container.auditSinks.delete",
                  "container.auditSinks.get",
                  "container.clusters.create",
                  "container.clusters.get",
                  "container.clusters.list",
                  "container.clusters.delete",
                  "container.clusters.getCredentials",
                  "iam.roles.list",
                  "iam.serviceAccounts.actAs",
                  "iam.serviceAccounts.get",
                  "iam.serviceAccounts.list",
                  "resourcemanager.projects.get"]
}