# -----------------------------------------------
# Code generated by infractl. DO NOT EDIT. GCP
# _       __     __    ______     __ __      __             __
#| |     / /__  / /_  / ____/  __/ //_/_  __/ /_  ___  ____/ /
#| | /| / / _ \/ __ \/ __/ | |/_/ ,< / / / / __ \/ _ \/ __  /
#| |/ |/ /  __/ /_/ / /____>  </ /| / /_/ / /_/ /  __/ /_/ /
#|__/|__/\___/_.___/_____/_/|_/_/ |_\__,_/_.___/\___/\__,_/
#
# codegen-version: v7.4.4
# template-version: EXPERIMENTAL
# -----------------------------------------------

data "google_client_config" "default" {}

data "vault_generic_secret" "gcp_infra_credential" {
  path=replace("secret/data/eticcprod/infra/scratch/gcp-test", "/data/", "/")
}

resource "google_project_iam_custom_role" "palladium-role" {
  role_id     = "palladium"
  title       = "Palladium Role"
  description = "Palladium access to GCP services like STT, Image recognition"
  permissions = ["iam.roles.list", "resourcemanager.projects.get", "firebase.projects.get"]
}

module "service_accounts" {
  source        = "terraform-google-modules/service-accounts/google"
  version       = "~> 3.0"
  project_id    = var.project_id
  prefix        = var.prefix
  names         = ["service-account"]
  project_roles = ["${var.project_id}=>roles/${google_project_iam_custom_role.palladium-role.role_id}"]
  display_name  = "Palladium Service Account"
  description   = "Palladium Service Account for Speech Services"
  generate_keys = true
  depends_on = [
    google_project_iam_custom_role.palladium-role
  ]
}

resource "vault_generic_secret" "palladium-service-account-secret" {
  path      = "secret/eticcprod/iam/gcp/palladium-service-account-keys"
  data_json = jsonencode(module.service_accounts.keys)
}